### ISSUE TITLE
Sample will not fail gracefully on speaker devices

### ISSUE THREAD

**Issue by arunjeetsingh** [alexa-labs/skill-sample-nodejs-movie-quotes-quiz#1]
On speaker devices that don't support APL, the current sample will fail with "...there is a problem with the skill response...". Instead, the sample should detect APL support on a device and if it isn't found, provide a reasonable failover experience explaining that the sample is meant for a multimodal Alexa device.

**Comment by arunjeetsingh** [comment]
Repo maintainer(s), please see https://github.com/alexa-labs/skill-sample-nodejs-firetv-vlogs/pull/3 for how to fix this issue.

**Comment by CamiWilliams** [comment]
Done!
